import assert from 'node:assert/strict';
class Element {
 constructor(){this.children=[];this.attributes={};this.dataset={};this.handlers={};this.style={setProperty(k,v){this[k]=v;}};this.classes=new Set();this.classList={add:k=>this.classes.add(k),remove:k=>this.classes.delete(k),contains:k=>this.classes.has(k),toggle:(k,v)=>v?this.classes.add(k):this.classes.delete(k)};}
 append(...els){for(const el of els){if(el.parentNode)el.parentNode.children=el.parentNode.children.filter(child=>child!==el);el.parentNode=this;this.children.push(el);}}
 insertBefore(el,before){if(el.parentNode)el.parentNode.children=el.parentNode.children.filter(child=>child!==el);el.parentNode=this;const i=this.children.indexOf(before);this.children.splice(i<0?this.children.length:i,0,el);} get firstChild(){return this.children[0];} setAttribute(k,v){this.attributes[k]=v;} removeAttribute(k){delete this.attributes[k];}
 addEventListener(k,fn){this.handlers[k]=fn;} removeEventListener(k,fn){if(this.handlers[k]===fn)delete this.handlers[k];}
 querySelectorAll(){return [];} querySelector(){return path;} cloneNode(){return new Element();} remove(){this.removed=true;Object.values(ids).forEach(el=>el.children=el.children.filter(child=>child!==this));}
 getBoundingClientRect(){return {left:50,top:300,width:500,height:433};}
}
const ids=Object.fromEntries(['motion-toggle','impact-grid','making-beads','twin-beads','design-svg','kept-cord','twin-cord','builder','impact-travel-beads'].map(id=>[id,new Element()]));
const prologue=new Element(),journey=new Element(),backdrop=new Element(),destination=new Element(),world=new Element();
const root=new Element(),opening=new Element(),studio=new Element(),path=new Element(),thread=new Element(),paper=new Element(),main=new Element(),shortcut=new Element();
const articles=Array.from({length:3},()=>new Element());const img=new Element();img.complete=true;img.naturalWidth=100;
main.querySelectorAll=()=>[img];
const chapters=['prologue','opening','making','impact'].map(chapter=>{const el=new Element();el.dataset.chapter=chapter;return el;});
journey.append(chapters[0],chapters[1]);chapters[0].append(prologue);chapters[1].append(opening);opening.append(world);opening.querySelector=()=>world;
const preference=new Element();preference.matches=false;
const documentHandlers={};
globalThis.document={documentElement:root,body:new Element(),hidden:false,getElementById:id=>ids[id],querySelector:q=>({'.prologue-scene':prologue,'.opening-journey':journey,'.camera-backdrop':backdrop,'.camera-destination':destination,'.opening-scene':opening,'.studio':studio,'main':main,'.making-thread':thread,'.paper-cutout':paper,'.impact-transition .scene':main}[q]),querySelectorAll:q=>q==='[data-chapter]'?chapters:q==='.how-copy article'?articles:q==='a[href="#builder"]'?[shortcut]:[],createElement:()=>new Element(),createElementNS:()=>new Element(),addEventListener(k,fn){documentHandlers[k]=fn;},removeEventListener(k){delete documentHandlers[k];}};
globalThis.innerWidth=1440;globalThis.innerHeight=900;globalThis.matchMedia=()=>preference;
let frameId=0;const frames=new Map();const flush=()=>{const batch=[...frames.values()];frames.clear();batch.forEach(fn=>fn());};
const windowHandlers={};
let scrollConfig;const triggers=[];globalThis.window={requestAnimationFrame(fn){frames.set(++frameId,fn);return frameId;},cancelAnimationFrame(id){frames.delete(id);},gsap:{registerPlugin(){}},ScrollTrigger:{config(value){scrollConfig=value;},create(config){const t={config,kill(){this.dead=true;}};triggers.push(t);return t;},refresh(){}},addEventListener(k,fn){windowHandlers[k]=fn;},removeEventListener(k){delete windowHandlers[k];}};
const {createPresentation}=await import('../js/presentation.js');
const api=createPresentation();assert.equal(main.style['--far-y'],'56.2%');assert.equal(ids['impact-grid'].children.length,650);assert.equal(ids['making-beads'].children.length,18);assert.equal(ids['twin-beads'].children.length,18);assert.equal(triggers.length,5);assert.equal(scrollConfig.ignoreMobileResize,true);assert.equal(scrollConfig.autoRefreshEvents,'DOMContentLoaded,load');
api.setProgress('prologue',.2);const prologueBefore=JSON.stringify(prologue.style);api.setProgress('prologue',1);assert.equal(destination.style.transform,'translate(0px,0px) scale(1,1)','actual source reaches full viewport');assert.equal(opening.parentNode,journey,'one scene owns both chapters');assert.equal(world.parentNode,destination,'existing world is the destination');api.setProgress('prologue',.2);assert.equal(JSON.stringify(prologue.style),prologueBefore);assert.equal(prologue.style['--prologue-first'],1);
api.setProgress('opening',.25);const before=JSON.stringify(opening.style);api.setProgress('opening',.9);api.setProgress('opening',.25);assert.equal(JSON.stringify(opening.style),before,'reverse state must match');
const prologueTrigger=triggers[0].config;
prologueTrigger.onUpdate({progress:.5});prologueTrigger.onUpdate({progress:.6});assert.equal(frames.size,1,'scroll updates coalesce');flush();assert.equal(prologue.style['--prologue-first'],0);
prologueTrigger.onUpdate({progress:.8});api.setProgress('prologue',.2);flush();assert.equal(prologue.style['--prologue-first'],1,'direct progress wins over older queued scroll');
document.hidden=true;documentHandlers.visibilitychange();prologueTrigger.onUpdate({progress:.2});assert.equal(frames.size,0,'hidden tab schedules no frame');document.hidden=false;documentHandlers.visibilitychange();flush();assert.equal(prologue.style['--prologue-first'],1);
document.hidden=true;documentHandlers.visibilitychange();globalThis.innerWidth=390;globalThis.innerHeight=844;windowHandlers.resize();assert.equal(frames.size,0);document.hidden=false;documentHandlers.visibilitychange();api.setProgress('impact',.4);const floating=document.body.children.find(el=>el.classes.has('handoff-bracelet'));assert.ok(Math.abs(Number(floating.style.transform.match(/translate\([^,]+,([^)]+)px/)[1])-(844-390*.28*.866-24))<.001,'hidden rotation updates cached viewport');globalThis.innerWidth=1440;globalThis.innerHeight=900;windowHandlers.resize();flush();
let reads=0;const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(){reads++;return rect.call(this);};
api.setProgress('impact',.4);api.setProgress('handoff',.4);assert.equal(reads,0,'render uses cached geometry');api.refresh();assert.ok(reads>0,'refresh remeasures');Element.prototype.getBoundingClientRect=rect;
api.setProgress('making',.65);assert.match(ids['twin-beads'].attributes.transform,/scale/,'twin travels as a group');const twinState={...ids['twin-beads'].attributes};const beads=ids['making-beads'].children.map(e=>({...e.attributes}));api.setProgress('making',1);assert.match(ids['twin-cord'].attributes.transform,/scale/);api.setProgress('making',.65);assert.deepEqual(ids['making-beads'].children.map(e=>e.attributes),beads);assert.deepEqual(ids['twin-beads'].attributes,twinState);
api.setProgress('impact',.5);assert.equal(ids['impact-grid'].children.filter(e=>e.style.opacity==='1').length,325);api.setProgress('impact',1);assert.equal(ids['impact-grid'].children.filter(e=>e.style.opacity==='1').length,650);
api.setProgress('handoff',.5);assert.equal(studio.inert,true);shortcut.handlers.click();assert.equal(studio.inert,false);assert.equal(ids['design-svg'].style.opacity,'1');
api.setPaused(true);assert.ok(root.classes.has('still'));assert.equal(opening.parentNode,chapters[1]);assert.equal(world.parentNode,opening);assert.equal(prologue.parentNode,chapters[0]);assert.ok(triggers.every(t=>t.dead));assert.ok(articles.every(e=>e.style.opacity==='1'));api.setPaused(false);assert.ok(root.classes.has('cinematic'));
preference.matches=true;preference.handlers.change();assert.ok(root.classes.has('still'));assert.equal(ids['motion-toggle'].disabled,true);preference.matches=false;preference.handlers.change();
img.handlers.error();assert.ok(root.classes.has('still'));triggers.at(-2).config.onUpdate({progress:.4});assert.equal(frames.size,1);api.destroy();assert.equal(frames.size,0,'destroy cancels scheduled rendering');assert.equal(documentHandlers.visibilitychange,undefined);assert.equal(ids['motion-toggle'].handlers.click,undefined);assert.equal(studio.inert,false);assert.equal(ids['impact-grid'].children.length,0);
delete window.gsap;delete window.ScrollTrigger;const fallback=createPresentation();assert.ok(root.classes.has('still'));fallback.destroy();
window.gsap={registerPlugin(){throw new Error('animation init failure');}};window.ScrollTrigger={};const broken=createPresentation();assert.ok(root.classes.has('still'));broken.destroy();
console.log('PASS: 650 marks, 18 matching twin beads, deterministic forward/reverse states, handoff/shortcut, pause/resume, reduced motion, asset failure, missing libraries, cleanup. (DOM fixtures; not browser verification.)');
